reactive_node:
  ros__parameters:
    odom_topic_name: ego_racecar/odom
    look_ahead_dist: 8.0
    width_heuristic: 0.0
    dist_heuristic: 0.5
    car_width: 0.2032
    gap_depth_diff: 0.75
    bubble_radius: 0.35
    panic_threshold: 4.0
    disparity_threshold: 0.75
    throttle_level_1: 0.5
    throttle_level_2: 0.5
    throttle_level_3: 0.5